name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: apps/web/pnpm-lock.yaml
      - run: pnpm --dir apps/web install
      - run: dotnet restore
      - run: dotnet format --verify-no-changes
      - run: dotnet build --no-restore
      - run: dotnet test --no-build -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:Threshold=80 -p:ThresholdType=line -p:ThresholdStat=total
      - run: pnpm --dir apps/web lint
      - run: pnpm --dir apps/web test --run --coverage
      - run: pnpm --dir apps/web build
